### ISSUE TITLE
Problem at the phone number stage

### ISSUE THREAD

**Issue by Vercingetoriks** [hyt47/SteamDesktopAuthenticator-Modded#1]
I'm trying to run the XP version and this is what happens:

The program loads fine and I click "Setup New Account". I'm asked for my Steam login details and provide them. A screen pops up asking for the Steam Guard code that was sent to my e-mail. I enter it and click "Accept". A new screen asks for my phone number. I enter it and click "Accept". The window becomes unresponsive for a second, then closes, followed immediately by the window that was asking for my login details. No error messages, and I'm left at the program's main screen. Tried it 8 times already with different phone formatting, and I still haven't received a single SMS.

I have the dependencies, Steam is open, and the phone number I'm trying to use has already been added to my Steam account. Any ideas?

**Comment by hyt47** [comment]
running a few tests... I'll be back with an answer

**Comment by hyt47** [comment]
new version released v0.3.1.1
Setup Instructions changed, You need to have XP Service Pack 3 to run this app

**Comment by Vercingetoriks** [comment]
Awesome, thank you! The program recognized that I had a phone attached to my Steam account already and just sent an SMS to it immediately. Everything else worked fine as well.

**Comment by hyt47** [comment]
Ok cool :)
